/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { JuryLogic, JuryLogicInterface } from "../JuryLogic";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "minStake",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "alpha",
        type: "uint256",
      },
    ],
    name: "calcTokenToFreeze",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
] as const;

export class JuryLogic__factory {
  static readonly abi = _abi;
  static createInterface(): JuryLogicInterface {
    return new utils.Interface(_abi) as JuryLogicInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): JuryLogic {
    return new Contract(address, _abi, signerOrProvider) as JuryLogic;
  }
}
