/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { InviterLogic, InviterLogicInterface } from "../InviterLogic";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "currencyValue",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "affiliateShare",
        type: "uint256",
      },
    ],
    name: "calcInviterRewards",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "currencyValue",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "affiliateShare",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "lvl0AffiliateShare",
            type: "uint256",
          },
        ],
        internalType: "struct InputTypes.CalcInvitersRewardsInput",
        name: "params",
        type: "tuple",
      },
    ],
    name: "calcInvitersRewards",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "inviter0Rewards",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "inviter1Rewards",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "remainingRewards",
            type: "uint256",
          },
        ],
        internalType: "struct OutputTypes.CalcInvitersRewardsOutput",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
] as const;

export class InviterLogic__factory {
  static readonly abi = _abi;
  static createInterface(): InviterLogicInterface {
    return new utils.Interface(_abi) as InviterLogicInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): InviterLogic {
    return new Contract(address, _abi, signerOrProvider) as InviterLogic;
  }
}
