/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export interface RoleKeysInterface extends utils.Interface {
  functions: {
    "BLACKLIST_ROLE()": FunctionFragment;
    "BUYER_ADMIN_ROLE()": FunctionFragment;
    "BUYER_ROLE()": FunctionFragment;
    "JUDGE_ROLE()": FunctionFragment;
    "PROTOCOL_ADMIN_ROLE()": FunctionFragment;
    "SELLER_ADMIN_ROLE()": FunctionFragment;
    "SELLER_ROLE()": FunctionFragment;
    "WHITELIST_ROLE()": FunctionFragment;
    "XP_GIVER_ROLE()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "BLACKLIST_ROLE"
      | "BUYER_ADMIN_ROLE"
      | "BUYER_ROLE"
      | "JUDGE_ROLE"
      | "PROTOCOL_ADMIN_ROLE"
      | "SELLER_ADMIN_ROLE"
      | "SELLER_ROLE"
      | "WHITELIST_ROLE"
      | "XP_GIVER_ROLE"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "BLACKLIST_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "BUYER_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "BUYER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "JUDGE_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PROTOCOL_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SELLER_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SELLER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "WHITELIST_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "XP_GIVER_ROLE",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "BLACKLIST_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "BUYER_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "BUYER_ROLE", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "JUDGE_ROLE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "PROTOCOL_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SELLER_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SELLER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "WHITELIST_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "XP_GIVER_ROLE",
    data: BytesLike
  ): Result;

  events: {};
}

export interface RoleKeys extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: RoleKeysInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    BLACKLIST_ROLE(overrides?: CallOverrides): Promise<[string]>;

    BUYER_ADMIN_ROLE(overrides?: CallOverrides): Promise<[string]>;

    BUYER_ROLE(overrides?: CallOverrides): Promise<[string]>;

    JUDGE_ROLE(overrides?: CallOverrides): Promise<[string]>;

    PROTOCOL_ADMIN_ROLE(overrides?: CallOverrides): Promise<[string]>;

    SELLER_ADMIN_ROLE(overrides?: CallOverrides): Promise<[string]>;

    SELLER_ROLE(overrides?: CallOverrides): Promise<[string]>;

    WHITELIST_ROLE(overrides?: CallOverrides): Promise<[string]>;

    XP_GIVER_ROLE(overrides?: CallOverrides): Promise<[string]>;
  };

  BLACKLIST_ROLE(overrides?: CallOverrides): Promise<string>;

  BUYER_ADMIN_ROLE(overrides?: CallOverrides): Promise<string>;

  BUYER_ROLE(overrides?: CallOverrides): Promise<string>;

  JUDGE_ROLE(overrides?: CallOverrides): Promise<string>;

  PROTOCOL_ADMIN_ROLE(overrides?: CallOverrides): Promise<string>;

  SELLER_ADMIN_ROLE(overrides?: CallOverrides): Promise<string>;

  SELLER_ROLE(overrides?: CallOverrides): Promise<string>;

  WHITELIST_ROLE(overrides?: CallOverrides): Promise<string>;

  XP_GIVER_ROLE(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    BLACKLIST_ROLE(overrides?: CallOverrides): Promise<string>;

    BUYER_ADMIN_ROLE(overrides?: CallOverrides): Promise<string>;

    BUYER_ROLE(overrides?: CallOverrides): Promise<string>;

    JUDGE_ROLE(overrides?: CallOverrides): Promise<string>;

    PROTOCOL_ADMIN_ROLE(overrides?: CallOverrides): Promise<string>;

    SELLER_ADMIN_ROLE(overrides?: CallOverrides): Promise<string>;

    SELLER_ROLE(overrides?: CallOverrides): Promise<string>;

    WHITELIST_ROLE(overrides?: CallOverrides): Promise<string>;

    XP_GIVER_ROLE(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    BLACKLIST_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    BUYER_ADMIN_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    BUYER_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    JUDGE_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    PROTOCOL_ADMIN_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    SELLER_ADMIN_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    SELLER_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    WHITELIST_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    XP_GIVER_ROLE(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    BLACKLIST_ROLE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    BUYER_ADMIN_ROLE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    BUYER_ROLE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    JUDGE_ROLE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    PROTOCOL_ADMIN_ROLE(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    SELLER_ADMIN_ROLE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    SELLER_ROLE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    WHITELIST_ROLE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    XP_GIVER_ROLE(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
