/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Errors } from "./Errors";
export type { RegistryKeys } from "./RegistryKeys";
export type { RoleKeys } from "./RoleKeys";
export type { XPKeys } from "./XPKeys";
