/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../../common";
import type {
  InvoiceLogic,
  InvoiceLogicInterface,
} from "../../../../protocol/libraries/logics/InvoiceLogic";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "price",
        type: "uint256",
      },
      {
        components: [
          {
            internalType: "uint256",
            name: "flat",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "percent",
            type: "uint256",
          },
        ],
        internalType: "struct DataTypes.FeeParams",
        name: "buyerFees",
        type: "tuple",
      },
    ],
    name: "calcBuyerFee",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "price",
        type: "uint256",
      },
      {
        components: [
          {
            internalType: "uint256",
            name: "flat",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "percent",
            type: "uint256",
          },
        ],
        internalType: "struct DataTypes.FeeParams",
        name: "sellerFees",
        type: "tuple",
      },
    ],
    name: "calcSellerFee",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
] as const;

const _bytecode =
  "0x61034161003a600b82828239805160001a60731461002d57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600436106100615760003560e01c80631a9d78131461006657806378645da714610066578063b92aa3c01461008f578063da6e40d5146100a2578063f4b84e59146100cf575b600080fd5b610079610074366004610286565b6100e2565b60405161008691906102bd565b60405180910390f35b61007961009d366004610209565b610109565b8180156100ae57600080fd5b506100c26100bd366004610221565b610122565b60405161008691906102b2565b6100796100dd366004610209565b610176565b80516020820151600091906100f8908590610189565b61010291906102c6565b9392505050565b6002810154815460009161011c916102de565b92915050565b838555600061013185846100e2565b600187015561014085836100e2565b6002870155504260038601556004850180546001600160a01b0385166001600160a01b0319909116179055600195945050505050565b6001810154815460009161011c916102c6565b6000811561138819839004841115176101a157600080fd5b506127109102611388010490565b6000604082840312156101c0578081fd5b6040516040810181811067ffffffffffffffff821117156101ef57634e487b7160e01b83526041600452602483fd5b604052823581526020928301359281019290925250919050565b60006020828403121561021a578081fd5b5035919050565b600080600080600060e08688031215610238578081fd5b853594506020860135935060408601356001600160a01b038116811461025c578182fd5b925061026b87606088016101af565b915061027a8760a088016101af565b90509295509295909350565b60008060608385031215610298578182fd5b823591506102a984602085016101af565b90509250929050565b901515815260200190565b90815260200190565b600082198211156102d9576102d96102f5565b500190565b6000828210156102f0576102f06102f5565b500390565b634e487b7160e01b600052601160045260246000fdfea26469706673582212206c4756182f1d30771b814629840b45593f7a48a2a18c096edfa6c37fd50b4a5b64736f6c63430008000033";

type InvoiceLogicConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: InvoiceLogicConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class InvoiceLogic__factory extends ContractFactory {
  constructor(...args: InvoiceLogicConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<InvoiceLogic> {
    return super.deploy(overrides || {}) as Promise<InvoiceLogic>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): InvoiceLogic {
    return super.attach(address) as InvoiceLogic;
  }
  override connect(signer: Signer): InvoiceLogic__factory {
    return super.connect(signer) as InvoiceLogic__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): InvoiceLogicInterface {
    return new utils.Interface(_abi) as InvoiceLogicInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): InvoiceLogic {
    return new Contract(address, _abi, signerOrProvider) as InvoiceLogic;
  }
}
