/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IProtocolConfigurator,
  IProtocolConfiguratorInterface,
} from "../../interfaces/IProtocolConfigurator";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "version",
        type: "uint256",
      },
    ],
    name: "getBuyerEntryParams",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "currencyValue",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "timeAdded",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "xpEarned",
            type: "uint256",
          },
          {
            internalType: "uint8",
            name: "invitationEarned",
            type: "uint8",
          },
        ],
        internalType: "struct DataTypes.EntryParams",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getBuyerEntryParams",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "currencyValue",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "timeAdded",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "xpEarned",
            type: "uint256",
          },
          {
            internalType: "uint8",
            name: "invitationEarned",
            type: "uint8",
          },
        ],
        internalType: "struct DataTypes.EntryParams",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "version",
        type: "uint256",
      },
    ],
    name: "getRetributionParams",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "affiliate",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "lvl0AffiliateShare",
            type: "uint256",
          },
        ],
        internalType: "struct DataTypes.RetributionParams",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getRetributionParams",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "affiliate",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "lvl0AffiliateShare",
            type: "uint256",
          },
        ],
        internalType: "struct DataTypes.RetributionParams",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IProtocolConfigurator__factory {
  static readonly abi = _abi;
  static createInterface(): IProtocolConfiguratorInterface {
    return new utils.Interface(_abi) as IProtocolConfiguratorInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IProtocolConfigurator {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IProtocolConfigurator;
  }
}
